### ISSUE TITLE
Will this remove propTypes that are assigned to a variable first?

### ISSUE THREAD

**Issue by lencioni** [nkt/babel-plugin-react-remove-prop-types#16]
Looking at the test suite, it isn't clear what will happen to code like the following:

```jsx
const propTypes = {
  foo: React.PropTypes.string
};

const Foo = () => (
  <div />
);

Foo.propTypes = propTypes;
```

I think that ideally it would be transformed to:

```jsx
const Foo = () => (
  <div />
);
```

**Comment by nkt** [comment]
Hm. I think this job of other plugin. Something like `babel-plugin-remove-unused-variables`. But I'll look into this and will come up with something.

**Comment by lencioni** [comment]
I see. That would require this plugin being applied first however.

**Comment by nkt** [comment]
This plugin deprecated. Use `babel-plugin-transform-react-remove-prop-types`.
