### ISSUE TITLE
`isStatelessComponent` method can fail

### ISSUE THREAD

**Issue by adamgruber** [nkt/babel-plugin-react-remove-prop-types#19]
https://github.com/nkt/babel-plugin-react-remove-prop-types/blob/master/src/is-stateless-component.js#L45

This line where you pass in `path.node.type` will fail if `path.node` is `undefined`. This error happened for me although I'm not sure why but you might want to add in a check.

**Comment by nkt** [comment]
This plugin deprecated. Use `babel-plugin-transform-react-remove-prop-types`.
