### ISSUE TITLE
Support for stateless components?

### ISSUE THREAD

**Issue by kentcdodds** [nkt/babel-plugin-react-remove-prop-types#5]
If this is supported, I can add documentation for an example. Something like:

**In**

```javascript
const Text = ({children}) => <p>{children}</p>
Text.propTypes = {children: React.PropTypes.string}
```

**Out**

```javascript
const Text = ({children}) => <p>{children}</p>
```

Also, technically I believe this is possible (although not recommended):

```javascript
const Text = ({children}) => {
  this.propTypes = {children: React.PropTypes.string}
  return <p>{children}</p>
}
```

I would expect the output to be:

```javascript
const Text = ({children}) => {
  return <p>{children}</p>
}
```

**Comment by Sinewyk** [comment]
I think that https://github.com/andrewimm/babel-plugin-remove-proptypes already does the job. It's meant to be used on class, but considering how the plugin is actually implemented https://github.com/andrewimm/babel-plugin-remove-proptypes/blob/master/src/index.js#L5-L7, it should work both for classes and stateless components.

**Comment by oliviertassinari** [comment]
If this can help, I have added the support for stateless functionnal component on my fork. Here is the link https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types/releases/tag/v0.2.0.

**Comment by kentcdodds** [comment]
Awesome. Thank you!
