### ISSUE TITLE
Support Babel 6

### ISSUE THREAD

**Issue by oliviertassinari** [nkt/babel-plugin-react-remove-prop-types#7]
Is this supported?

**Comment by ninja-** [comment]
+1

**Comment by oliviertassinari** [comment]
If this might help, I have just finised migrating my plugin to babel 6: https://github.com/oliviertassinari/babel-plugin-react-remove-properties/blob/master/src/index.js.

**Comment by ninja-** [comment]
@oliviertassinari I tried to port this plugin today but gave up, I can have a second look and try to base it on your plugin

**Comment by oliviertassinari** [comment]
My plugin is really simple and it's based on this one. I'm not sure that starting from mine will help :grin:

**Comment by ninja-** [comment]
:neutral_face: are your tests working on babel 6?

**Comment by oliviertassinari** [comment]
Yes, they do.

**Comment by oliviertassinari** [comment]
@ninja- Where are you with the port? I'm gonna try otherwise.
I have done a bit more complex plugin with babel6, It may help too https://github.com/oliviertassinari/babel-plugin-transform-dev-warning.

**Comment by oliviertassinari** [comment]
@ninja- I'm waiting my PR to be merged. I ended up publishing a fork of this repo https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types

**Comment by ninja-** [comment]
@olivierassinari that's nice, thanks! I'll have a look

**Comment by NogsMPLS** [comment]
I also went ahead and forked @oliviertassinari's fork of this repo and made a flexible 'static agnostic' removal plugin:

https://github.com/NogsMPLS/babel-plugin-transform-react-remove-statics

basically in babelrc, you can define what statics you want to remove in case there are any other libraries you use that utilize statics (like https://github.com/theogravity/react-styleguide-generator-alt )

**Comment by nkt** [comment]
I'm working on this.

**Comment by nkt** [comment]
I've just published 2.0.0!

**Comment by dictions** [comment]
Yay, thank you @nkt!

**Comment by vvo** [comment]
Dunno why, but I still had to use https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types otherwise it would not remove any proptype..

**Comment by nkt** [comment]
@vvo can you provide some code?

**Comment by vvo** [comment]
That's a whole application so isolating the code might be hard. Maybe because we were using require instead of ES6 import on ES6 exported components. Will have to check again and give feedback here
